import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-200 bg-gradient-to-br from-[#06102a] via-[#3a0544] to-[#470e57] animate-gradient min-h-screen flex flex-col`}
      >
        <Navbar />


        <div className="flex-grow">{children}</div>

        <div className="w-32 h-1 bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 rounded-full  mb-12 mx-auto" />

        <Footer />
      </body>
    </html>

  );
}
